### ISSUE TITLE
It's not moving.

### ISSUE THREAD

**Issue by PDL2CGamejolt** [TheLeerName/ShadertoyToFlixel#4]
I got the distorted TV shader from Shadertoy to use in my FNF mod and I used the web version to convert it to Flixel and the shader works... but it's not moving.

**Comment by PDL2CGamejolt** [comment]
nvm

**Comment by daveandbambifan1234** [comment]
> Authorit happened with me but it was much more broken instead what happened is that it kept converting to the same thing
