### ISSUE TITLE
the image explains all of it

### ISSUE THREAD

**Issue by daveandbambifan1234** [TheLeerName/ShadertoyToFlixel#7]
![yeah](https://github.com/TheLeerName/ShadertoyToFlixel/assets/159091869/e9372dbc-b12a-4c06-bb82-042d9ec84577)

let me know if you need more context

**Comment by TheLeerName** [comment]
cuz it works like this???

**Comment by daveandbambifan1234** [comment]
> cuz it works like this???

even typing one thing can cause it to break the entire thing
